from __future__ import annotations


STYLE = """
:root{color-scheme:dark;--bg:#101715;--panel:#17211e;--line:#2c3b36;--ink:#edf7f2;--muted:#9db2a9;--accent:#4bd09b;--danger:#ff8f8f}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 system-ui,sans-serif}main{width:min(1100px,94vw);margin:30px auto 80px}
h1,h2{margin:.2em 0 .7em}header{display:flex;align-items:center;justify-content:space-between;gap:20px}section,.post,.card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:18px;margin:18px 0}
label{display:block;color:var(--muted);margin:10px 0 4px}input,select,button{font:inherit;color:var(--ink);background:#0d1412;border:1px solid var(--line);border-radius:8px;padding:9px 11px}input{width:100%}button{cursor:pointer;background:#1f604a}button.secondary{background:#26332f}button:disabled{cursor:not-allowed;opacity:.7}button[data-loading="true"]{cursor:progress}
.status{padding:6px 10px;border:1px solid var(--line);border-radius:999px;color:var(--accent)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}.grid .card{margin:0;display:flex;flex-direction:column}.card:hover{border-color:var(--accent)}
.row{display:flex;gap:10px;align-items:end}.row>*{flex:1}.row button{flex:0 0 auto}.days-filter{display:flex;align-items:center;gap:6px;margin:0;white-space:nowrap}.days-filter input{width:90px}.target-settings{display:flex;align-items:flex-end;gap:14px;padding:12px 14px;margin:14px 0}.target-settings>strong{align-self:center;white-space:nowrap}.target-settings form{display:flex;align-items:flex-end;gap:12px;flex:1}.target-settings label{margin:0}.target-settings .tracking-toggle{display:flex;align-items:center;gap:7px;padding:9px 0;white-space:nowrap}.target-settings .tracking-toggle input{width:auto}.target-settings .backfill{flex:0 0 auto}.target-settings input[type=number]{width:110px}.notification-control{display:flex;flex-direction:column;align-items:flex-start;gap:2px}.notification-control .muted{font-size:12px;max-width:280px}header .notification-control{align-items:flex-end;text-align:right}.rule-editor>summary,#disabled-rules>summary{cursor:pointer;font-weight:700;color:var(--ink)}.rule-editor>summary{font-size:1.5em;line-height:1.2}h3,#disabled-rules>summary{font-size:1.17em;line-height:1.2}.rule-editor[open]>summary{margin-bottom:14px}.rule-notifications{border:1px solid var(--line);border-radius:8px;margin:14px 0;padding:8px 12px 12px}.rule-notifications label{display:inline-flex;align-items:center;gap:6px;margin-right:18px}.rule-notifications input{width:auto}#disabled-rules{margin-top:16px;border-top:1px solid var(--line);padding-top:14px}.muted{color:var(--muted)}.match{color:var(--accent)}.deleted,.danger{color:var(--danger)}.post p{white-space:pre-wrap}.meta{display:flex;gap:12px;flex-wrap:wrap;color:var(--muted);font-size:13px}.rule{display:flex;justify-content:space-between;align-items:flex-start;gap:10px;padding:10px 0;border-top:1px solid var(--line)}.rule>div:first-child{flex:1;min-width:0}.rule>div:first-child .muted{overflow-wrap:anywhere}.rule>div:last-child{display:flex;flex:0 0 auto;gap:6px;white-space:nowrap}.rule>div:last-child button{padding-inline:8px}a{color:#7bdcb6;text-decoration:none}.card-link{color:inherit}.spacer{flex:1}.back{display:inline-block;margin-bottom:16px}@media(max-width:760px){.row,.target-settings,.target-settings form{flex-wrap:wrap}.target-settings>strong{width:100%}header .notification-control{align-items:flex-start;text-align:left}}
"""


BROWSER_ALERT_SCRIPT = """
function updateBrowserAlertState(permission) {
  const button=$('#notify'),status=$('#notify-status');
  if(!button||!status)return;
  delete button.dataset.loading;
  if(!('Notification' in window)){button.disabled=true;button.textContent='Browser alerts unavailable';status.textContent='Notifications are not supported by this browser.';return}
  if(permission==='granted'){button.disabled=true;button.textContent='Browser alerts enabled';status.textContent='Permission granted.';return}
  if(permission==='denied'){button.disabled=false;button.textContent='Browser alerts blocked';status.textContent='Click for steps to unblock notifications.';return}
  button.disabled=false;button.textContent='Enable browser alerts';status.textContent='Permission has not been requested.';
}
function showBrowserAlertHelp(){
  const status=$('#notify-status'),ua=navigator.userAgent;
  if(/Safari/.test(ua)&&!/Chrome|Chromium/.test(ua))status.textContent='Safari → Settings → Websites → Notifications → allow 127.0.0.1, then reload.';
  else if(/Firefox/.test(ua))status.textContent='Click the padlock by the address → Permissions → Notifications → Allow, then reload.';
  else status.textContent='Click the site-controls icon by the address → Site settings → Notifications → Allow, then reload.';
}
async function requestBrowserAlerts(){
  const button=$('#notify'),status=$('#notify-status');
  if(!('Notification' in window)){updateBrowserAlertState('unsupported');return}
  if(Notification.permission==='denied'){showBrowserAlertHelp();return}
  button.disabled=true;button.dataset.loading='true';button.textContent='Requesting…';status.textContent='Waiting for browser permission…';
  try{updateBrowserAlertState(await Notification.requestPermission())}catch(error){button.disabled=false;button.textContent='Enable browser alerts';status.textContent='Could not request permission: '+error.message}
}
function initializeBrowserAlerts(){
  updateBrowserAlertState('Notification' in window?Notification.permission:'unsupported');
  $('#notify').onclick=requestBrowserAlerts;
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)updateBrowserAlertState('Notification' in window?Notification.permission:'unsupported')});
}
"""


def render_home() -> str:
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><title>Telegram Channel Tracker</title><style>{STYLE}</style></head>
<body><main><header><div><h1>Telegram Channel Tracker</h1><div class="muted">Tracked channels and topics</div></div><div class="notification-control"><button id="notify" class="secondary" type="button">Enable browser alerts</button><span id="notify-status" class="muted" role="status" aria-live="polite"></span></div></header>
<section><h2>Add channel or topic</h2><form id="add-form" class="row"><div><label>Telegram username, channel link, or topic link</label><input name="channel_ref" required placeholder="https://t.me/c/123456/789"></div><div><label>Initial posts</label><input name="backfill_limit" type="number" min="1" max="10000" value="100"></div><button>Add</button></form><label><input id="saved-alerts" type="checkbox" style="width:auto"> Send live matches to Telegram Saved Messages</label><label><input id="email-alerts" type="checkbox" style="width:auto"> Send live matches by email</label><div id="email-status" class="muted"></div><label><input id="bot-alerts" type="checkbox" style="width:auto"> Send incoming alerts from a Telegram bot</label><div id="bot-status" class="muted"></div><div id="error" class="danger"></div></section>
<div id="cards" class="grid"></div></main><script>
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
{BROWSER_ALERT_SCRIPT}
async function api(url,options={{}}){{const r=await fetch(url,{{headers:{{'Content-Type':'application/json'}},...options}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}}
function card(t){{return `<a class="card-link" href="/channels/${{t.id}}"><article class="card"><div><span class="status">${{esc(t.status)}}</span></div><h2>${{esc(t.title)}}</h2><div class="muted">${{t.topic_id?'Topic '+t.topic_id:'Entire channel'}}</div><div class="spacer"></div><p>${{t.post_count}} posts · ${{t.matched_count}} matched<br>${{t.enabled_rule_count}} enabled rules</p><div class="muted">${{t.last_posted_at?'Latest '+new Date(t.last_posted_at).toLocaleString():'No posts yet'}}</div></article></a>`}}
async function load(){{const targets=await api('/api/targets');$('#cards').innerHTML=targets.map(card).join('')||'<p class="muted">No channels configured.</p>'}}function applyPreferences(p){{$('#saved-alerts').checked=p.saved_messages_alerts;const email=$('#email-alerts');email.checked=p.email_alerts;email.disabled=!p.email_configured;$('#email-status').textContent=p.email_configured?`Email recipient: ${{p.email_recipient}}`:'Email is not configured. Run telegram-channel-tracker setup-email.';const bot=$('#bot-alerts');bot.checked=p.telegram_bot_alerts;bot.disabled=!p.telegram_bot_configured;$('#bot-status').textContent=p.telegram_bot_configured?`Incoming alerts from @${{p.telegram_bot_username}}`:'Telegram bot is not configured. Run telegram-channel-tracker setup-bot.'}}async function loadPreferences(){{applyPreferences(await api('/api/preferences'))}}async function savePreferences(){{const p=await api('/api/preferences',{{method:'PUT',body:JSON.stringify({{saved_messages_alerts:$('#saved-alerts').checked,email_alerts:$('#email-alerts').checked,telegram_bot_alerts:$('#bot-alerts').checked}})}});applyPreferences(p)}}
$('#add-form').onsubmit=async e=>{{e.preventDefault();$('#error').textContent='';const f=new FormData(e.target);try{{const t=await api('/api/targets',{{method:'POST',body:JSON.stringify({{channel_ref:f.get('channel_ref'),backfill_limit:+f.get('backfill_limit')}})}});location.href='/channels/'+t.id}}catch(err){{$('#error').textContent=err.message}}}};
$('#saved-alerts').onchange=savePreferences;$('#email-alerts').onchange=savePreferences;$('#bot-alerts').onchange=savePreferences;function connect(){{const ws=new WebSocket(`${{location.protocol==='https:'?'wss':'ws'}}://${{location.host}}/api/live`);ws.onmessage=e=>{{const x=JSON.parse(e.data);if(x.type==='targets_updated'||x.type==='post_created'||x.type==='post_updated')load();if(x.notify&&'Notification' in window&&Notification.permission==='granted')new Notification('Telegram channel alert',{{body:(x.post?.text||'Matched post').slice(0,180)}})}};ws.onclose=()=>setTimeout(connect,2000)}}initializeBrowserAlerts();Promise.all([load(),loadPreferences()]);connect();
</script></body></html>"""


def render_dashboard(target_id: int = 1) -> str:
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><title>Telegram Channel Tracker</title><style>{STYLE}</style></head>
<body><main><a class="back" href="/">← All tracked channels</a><header><div><h1 id="title">Telegram target</h1><div id="subtitle" class="muted"></div></div><span id="status" class="status">loading</span></header>
<section class="target-settings" aria-label="Target settings"><strong>Target settings</strong><form id="target-form"><label class="tracking-toggle"><input name="enabled" type="checkbox"> Tracking enabled</label><label class="backfill"><span>Initial posts</span><input name="backfill_limit" type="number" min="1" max="10000"></label><button>Save</button></form><div class="notification-control"><button id="notify" class="secondary" type="button">Enable browser alerts</button><span id="notify-status" class="muted" role="status" aria-live="polite"></span></div></section>
<section><details id="rule-editor" class="rule-editor"><summary id="rule-editor-label">Add new rule</summary><form id="rule-form"><input name="id" type="hidden"><label>Rule name</label><input name="name" required><label>Include phrases (comma separated)</label><input name="include" required><div class="row"><div><label>Mode</label><select name="match_mode"><option value="any">Any phrase</option><option value="all">All phrases</option></select></div><div><label>Exclude phrases</label><input name="exclude"></div></div><label><input name="enabled" type="checkbox" style="width:auto" checked> Rule enabled</label><fieldset class="rule-notifications"><legend>Notifications for this rule</legend><label><input name="email_alerts" type="checkbox" checked> Email</label><label><input name="telegram_bot_alerts" type="checkbox" checked> Telegram</label><div class="muted">The matching global notification switch must also be enabled.</div></fieldset><p><button id="rule-submit">Add rule</button> <button id="rule-cancel" class="secondary" type="button" hidden>Cancel edit</button></p></form></details></section>
<section><h2>Keyword rules</h2><h3>Enabled rules</h3><div id="enabled-rules"></div><details id="disabled-rules"><summary>Disabled rules (<span id="disabled-rule-count">0</span>)</summary><div id="disabled-rule-list"></div></details></section>
<section><div class="row"><div><h2>Posts</h2><div id="archive-status" class="muted" role="status" aria-live="polite">Loading…</div></div><input id="search" placeholder="Search posts"><select id="matched"><option value="">All posts</option><option value="true">Matched</option><option value="false">Unmatched</option></select><label class="days-filter"><span>From</span><input id="days-ago" type="number" min="1" max="3650" step="1" placeholder="N"><span>days ago</span></label><button id="refresh" class="secondary" type="button">Refresh</button></div><div id="posts"></div></section></main><script>
const targetId={target_id},$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));async function api(url,options={{}}){{const r=await fetch(url,{{cache:'no-store',headers:{{'Content-Type':'application/json'}},...options}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}}
{BROWSER_ALERT_SCRIPT}
async function loadTarget(){{const t=await api(`/api/targets/${{targetId}}`);$('#title').textContent=t.title;$('#subtitle').textContent=t.topic_id?'Topic '+t.topic_id:'Entire channel';$('#status').textContent=t.status;$('#status').title=t.status_detail||'';const f=$('#target-form');f.elements.enabled.checked=t.enabled;f.elements.backfill_limit.value=t.backfill_limit}}
let rulesCache=[];function ruleHtml(r){{const channels=[r.email_alerts?'Email':'',r.telegram_bot_alerts?'Telegram':''].filter(Boolean).join(', ')||'None';return `<div class="rule"><div><b>${{esc(r.name)}}</b><div class="muted">${{esc(r.match_mode)}}: ${{esc(r.include_terms.join(', '))}}${{r.exclude_terms.length?' · exclude '+esc(r.exclude_terms.join(', ')):''}}</div><div class="muted">Notifications: ${{channels}}</div></div><div><button type="button" class="secondary" onclick="toggleRule(${{r.id}})">${{r.enabled?'Disable':'Enable'}}</button> <button type="button" class="secondary" onclick="editRule(${{r.id}})">Edit</button> <button type="button" class="secondary" onclick="deleteRule(${{r.id}})">Delete</button></div></div>`}}async function loadRules(){{rulesCache=await api(`/api/targets/${{targetId}}/rules`);const enabled=rulesCache.filter(r=>r.enabled),disabled=rulesCache.filter(r=>!r.enabled);$('#enabled-rules').innerHTML=enabled.map(ruleHtml).join('')||'<p class="muted">No enabled rules.</p>';$('#disabled-rule-list').innerHTML=disabled.map(ruleHtml).join('');$('#disabled-rule-count').textContent=disabled.length;$('#disabled-rules').hidden=!disabled.length}}
function editRule(id){{const r=rulesCache.find(x=>x.id===id),f=$('#rule-form');if(!r)return;f.elements.id.value=r.id;f.elements.name.value=r.name;f.elements.include.value=r.include_terms.join(', ');f.elements.exclude.value=r.exclude_terms.join(', ');f.elements.match_mode.value=r.match_mode;f.elements.enabled.checked=r.enabled;f.elements.email_alerts.checked=r.email_alerts;f.elements.telegram_bot_alerts.checked=r.telegram_bot_alerts;$('#rule-submit').textContent='Save changes';$('#rule-cancel').hidden=false;$('#rule-editor-label').textContent='Edit rule';$('#rule-editor').open=true;$('#rule-editor').scrollIntoView({{behavior:'smooth',block:'start'}})}}function resetRuleForm(){{const f=$('#rule-form');f.reset();f.elements.id.value='';$('#rule-submit').textContent='Add rule';$('#rule-cancel').hidden=true;$('#rule-editor-label').textContent='Add new rule';$('#rule-editor').open=false}}
async function toggleRule(id){{const r=rulesCache.find(x=>x.id===id);await api(`/api/targets/${{targetId}}/rules/${{id}}`,{{method:'PUT',body:JSON.stringify({{name:r.name,include_terms:r.include_terms,exclude_terms:r.exclude_terms,match_mode:r.match_mode,enabled:!r.enabled,email_alerts:r.email_alerts,telegram_bot_alerts:r.telegram_bot_alerts}})}});loadRules();loadPosts()}}async function deleteRule(id){{if(confirm('Delete this rule?')){{await api(`/api/targets/${{targetId}}/rules/${{id}}`,{{method:'DELETE'}});loadRules();loadPosts()}}}}
function postHtml(p){{const badges=p.matched_rule_names.map(x=>`<span class="match">● ${{esc(x)}}</span>`).join(' ');return `<article class="post"><div class="meta"><span>${{new Date(p.posted_at).toLocaleString()}}</span>${{badges}}${{p.edited_at?'<span>edited</span>':''}}${{p.deleted_at?'<span class="deleted">deleted</span>':''}}</div><p>${{esc(p.text)}}</p>${{p.post_url?`<p><a target="_blank" rel="noreferrer" href="${{esc(p.post_url)}}">Open in Telegram ↗</a></p>`:''}}</article>`}}async function loadPosts(){{const status=$('#archive-status');status.textContent='Loading…';try{{const q=new URLSearchParams({{q:$('#search').value,limit:'100'}});if($('#matched').value)q.set('matched',$('#matched').value);if($('#days-ago').value)q.set('days',$('#days-ago').value);const posts=await api(`/api/targets/${{targetId}}/posts?`+q);$('#posts').innerHTML=posts.map(postHtml).join('')||'<p class="muted">No archived posts.</p>';status.textContent=`Showing ${{posts.length}} post${{posts.length===1?'':'s'}} · Updated ${{new Date().toLocaleTimeString()}}`;return posts}}catch(err){{status.textContent='Refresh failed: '+err.message;throw err}}}}async function refreshPosts(){{const button=$('#refresh');button.disabled=true;button.textContent='Refreshing…';try{{await loadPosts()}}finally{{button.disabled=false;button.textContent='Refresh'}}}}
$('#target-form').onsubmit=async e=>{{e.preventDefault();const f=new FormData(e.target);await api(`/api/targets/${{targetId}}`,{{method:'PUT',body:JSON.stringify({{enabled:f.get('enabled')==='on',backfill_limit:+f.get('backfill_limit')}})}});loadTarget()}};$('#rule-form').onsubmit=async e=>{{e.preventDefault();const f=new FormData(e.target),terms=x=>String(x||'').split(',').map(x=>x.trim()).filter(Boolean),id=f.get('id'),payload={{name:f.get('name'),include_terms:terms(f.get('include')),exclude_terms:terms(f.get('exclude')),match_mode:f.get('match_mode'),enabled:f.get('enabled')==='on',email_alerts:f.get('email_alerts')==='on',telegram_bot_alerts:f.get('telegram_bot_alerts')==='on'}};await api(id?`/api/targets/${{targetId}}/rules/${{id}}`:`/api/targets/${{targetId}}/rules`,{{method:id?'PUT':'POST',body:JSON.stringify(payload)}});resetRuleForm();loadRules();loadPosts()}};$('#rule-cancel').onclick=resetRuleForm;$('#refresh').onclick=refreshPosts;$('#matched').onchange=loadPosts;let timer;function schedulePosts(){{clearTimeout(timer);timer=setTimeout(loadPosts,250)}}$('#search').oninput=schedulePosts;$('#days-ago').oninput=schedulePosts;
function connect(){{const ws=new WebSocket(`${{location.protocol==='https:'?'wss':'ws'}}://${{location.host}}/api/live`);ws.onmessage=e=>{{const x=JSON.parse(e.data);if(x.type==='targets_updated')loadTarget();if((x.type==='post_created'||x.type==='post_updated')&&x.target_id===targetId){{loadPosts();if(x.notify&&'Notification' in window&&Notification.permission==='granted')new Notification('Telegram channel alert',{{body:(x.post.text||'Matched post').slice(0,180)}})}}}};ws.onclose=()=>setTimeout(connect,2000)}}initializeBrowserAlerts();Promise.all([loadTarget(),loadRules(),loadPosts()]);connect();
</script></body></html>"""
