from __future__ import annotations


STYLE = """
:root{color-scheme:dark;--bg:#101715;--panel:#17211e;--line:#2c3b36;--ink:#edf7f2;--muted:#9db2a9;--accent:#4bd09b;--danger:#ff8f8f}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 system-ui,sans-serif}main{width:min(1100px,94vw);margin:30px auto 80px}
h1,h2{margin:.2em 0 .7em}header{display:flex;align-items:center;justify-content:space-between;gap:20px}section,.post,.card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:18px;margin:18px 0}
label{display:block;color:var(--muted);margin:10px 0 4px}input,select,button{font:inherit;color:var(--ink);background:#0d1412;border:1px solid var(--line);border-radius:8px;padding:9px 11px}input{width:100%}button{cursor:pointer;background:#1f604a}button.secondary{background:#26332f}
.status{padding:6px 10px;border:1px solid var(--line);border-radius:999px;color:var(--accent)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}.grid .card{margin:0;display:flex;flex-direction:column}.card:hover{border-color:var(--accent)}
.row{display:flex;gap:10px;align-items:end}.row>*{flex:1}.row button{flex:0 0 auto}.muted{color:var(--muted)}.match{color:var(--accent)}.deleted,.danger{color:var(--danger)}.post p{white-space:pre-wrap}.meta{display:flex;gap:12px;flex-wrap:wrap;color:var(--muted);font-size:13px}.rule{display:flex;justify-content:space-between;align-items:flex-start;gap:10px;padding:10px 0;border-top:1px solid var(--line)}.rule>div:first-child{flex:1;min-width:0}.rule>div:first-child .muted{overflow-wrap:anywhere}.rule>div:last-child{display:flex;flex:0 0 auto;gap:6px;white-space:nowrap}.rule>div:last-child button{padding-inline:8px}a{color:#7bdcb6;text-decoration:none}.card-link{color:inherit}.spacer{flex:1}.back{display:inline-block;margin-bottom:16px}@media(max-width:760px){.row{flex-wrap:wrap}}
"""


def render_home() -> str:
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Telegram Channel Tracker</title><style>{STYLE}</style></head>
<body><main><header><div><h1>Telegram Channel Tracker</h1><div class="muted">Tracked channels and topics</div></div><button id="notify" class="secondary">Enable browser alerts</button></header>
<section><h2>Add channel or topic</h2><form id="add-form" class="row"><div><label>Telegram username, channel link, or topic link</label><input name="channel_ref" required placeholder="https://t.me/c/123456/789"></div><div><label>Initial posts</label><input name="backfill_limit" type="number" min="1" max="10000" value="100"></div><button>Add</button></form><label><input id="saved-alerts" type="checkbox" style="width:auto"> Send live matches to Telegram Saved Messages</label><div id="error" class="danger"></div></section>
<div id="cards" class="grid"></div></main><script>
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
async function api(url,options={{}}){{const r=await fetch(url,{{headers:{{'Content-Type':'application/json'}},...options}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}}
function card(t){{return `<a class="card-link" href="/channels/${{t.id}}"><article class="card"><div><span class="status">${{esc(t.status)}}</span></div><h2>${{esc(t.title)}}</h2><div class="muted">${{t.topic_id?'Topic '+t.topic_id:'Entire channel'}}</div><div class="spacer"></div><p>${{t.post_count}} posts · ${{t.matched_count}} matched<br>${{t.enabled_rule_count}} enabled rules</p><div class="muted">${{t.last_posted_at?'Latest '+new Date(t.last_posted_at).toLocaleString():'No posts yet'}}</div></article></a>`}}
async function load(){{const targets=await api('/api/targets');$('#cards').innerHTML=targets.map(card).join('')||'<p class="muted">No channels configured.</p>'}}async function loadPreferences(){{const p=await api('/api/preferences');$('#saved-alerts').checked=p.saved_messages_alerts}}
$('#add-form').onsubmit=async e=>{{e.preventDefault();$('#error').textContent='';const f=new FormData(e.target);try{{const t=await api('/api/targets',{{method:'POST',body:JSON.stringify({{channel_ref:f.get('channel_ref'),backfill_limit:+f.get('backfill_limit')}})}});location.href='/channels/'+t.id}}catch(err){{$('#error').textContent=err.message}}}};
$('#saved-alerts').onchange=e=>api('/api/preferences',{{method:'PUT',body:JSON.stringify({{saved_messages_alerts:e.target.checked}})}});$('#notify').onclick=()=>Notification.requestPermission();function connect(){{const ws=new WebSocket(`${{location.protocol==='https:'?'wss':'ws'}}://${{location.host}}/api/live`);ws.onmessage=e=>{{const x=JSON.parse(e.data);if(x.type==='targets_updated'||x.type==='post_created'||x.type==='post_updated')load();if(x.notify&&Notification.permission==='granted')new Notification('Telegram channel alert',{{body:(x.post?.text||'Matched post').slice(0,180)}})}};ws.onclose=()=>setTimeout(connect,2000)}}Promise.all([load(),loadPreferences()]);connect();
</script></body></html>"""


def render_dashboard(target_id: int = 1) -> str:
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Telegram Channel Tracker</title><style>{STYLE}</style></head>
<body><main><a class="back" href="/">← All tracked channels</a><header><div><h1 id="title">Telegram target</h1><div id="subtitle" class="muted"></div></div><span id="status" class="status">loading</span></header>
<div class="grid"><section><h2>Target settings</h2><form id="target-form"><label><input name="enabled" type="checkbox" style="width:auto"> Tracking enabled</label><label>Initial posts</label><input name="backfill_limit" type="number" min="1" max="10000"><p><button>Save</button></p></form><button id="notify" class="secondary">Enable browser alerts</button></section>
<section><h2>Keyword rules</h2><form id="rule-form"><input name="id" type="hidden"><label>Rule name</label><input name="name" required><label>Include phrases (comma separated)</label><input name="include" required><div class="row"><div><label>Mode</label><select name="match_mode"><option value="any">Any phrase</option><option value="all">All phrases</option></select></div><div><label>Exclude phrases</label><input name="exclude"></div></div><label><input name="enabled" type="checkbox" style="width:auto" checked> Rule enabled</label><p><button id="rule-submit">Add rule</button> <button id="rule-cancel" class="secondary" type="button" hidden>Cancel edit</button></p></form><div id="rules"></div></section></div>
<section><div class="row"><div><h2>Archived posts</h2></div><input id="search" placeholder="Search posts"><select id="matched"><option value="">All posts</option><option value="true">Matched</option><option value="false">Unmatched</option></select><button id="refresh" class="secondary">Refresh</button></div><div id="posts"></div></section></main><script>
const targetId={target_id},$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));async function api(url,options={{}}){{const r=await fetch(url,{{headers:{{'Content-Type':'application/json'}},...options}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}}
async function loadTarget(){{const t=await api(`/api/targets/${{targetId}}`);$('#title').textContent=t.title;$('#subtitle').textContent=t.topic_id?'Topic '+t.topic_id:'Entire channel';$('#status').textContent=t.status;$('#status').title=t.status_detail||'';const f=$('#target-form');f.elements.enabled.checked=t.enabled;f.elements.backfill_limit.value=t.backfill_limit}}
let rulesCache=[];async function loadRules(){{rulesCache=await api(`/api/targets/${{targetId}}/rules`);$('#rules').innerHTML=rulesCache.map(r=>`<div class="rule"><div><b>${{esc(r.name)}}</b> <span class="${{r.enabled?'match':'muted'}}">${{r.enabled?'enabled':'disabled'}}</span><div class="muted">${{esc(r.match_mode)}}: ${{esc(r.include_terms.join(', '))}}${{r.exclude_terms.length?' · exclude '+esc(r.exclude_terms.join(', ')):''}}</div></div><div><button class="secondary" onclick="toggleRule(${{r.id}})">${{r.enabled?'Disable':'Enable'}}</button> <button class="secondary" onclick="editRule(${{r.id}})">Edit</button> <button class="secondary" onclick="deleteRule(${{r.id}})">Delete</button></div></div>`).join('')||'<p class="muted">No rules yet.</p>'}}
function editRule(id){{const r=rulesCache.find(x=>x.id===id),f=$('#rule-form');if(!r)return;f.elements.id.value=r.id;f.elements.name.value=r.name;f.elements.include.value=r.include_terms.join(', ');f.elements.exclude.value=r.exclude_terms.join(', ');f.elements.match_mode.value=r.match_mode;f.elements.enabled.checked=r.enabled;$('#rule-submit').textContent='Save changes';$('#rule-cancel').hidden=false}}function resetRuleForm(){{const f=$('#rule-form');f.reset();f.elements.id.value='';$('#rule-submit').textContent='Add rule';$('#rule-cancel').hidden=true}}
async function toggleRule(id){{const r=rulesCache.find(x=>x.id===id);await api(`/api/targets/${{targetId}}/rules/${{id}}`,{{method:'PUT',body:JSON.stringify({{name:r.name,include_terms:r.include_terms,exclude_terms:r.exclude_terms,match_mode:r.match_mode,enabled:!r.enabled}})}});loadRules();loadPosts()}}async function deleteRule(id){{if(confirm('Delete this rule?')){{await api(`/api/targets/${{targetId}}/rules/${{id}}`,{{method:'DELETE'}});loadRules();loadPosts()}}}}
function postHtml(p){{const badges=p.matched_rule_names.map(x=>`<span class="match">● ${{esc(x)}}</span>`).join(' ');return `<article class="post"><div class="meta"><span>${{new Date(p.posted_at).toLocaleString()}}</span>${{badges}}${{p.edited_at?'<span>edited</span>':''}}${{p.deleted_at?'<span class="deleted">deleted</span>':''}}</div><p>${{esc(p.text)}}</p>${{p.post_url?`<p><a target="_blank" rel="noreferrer" href="${{esc(p.post_url)}}">Open in Telegram ↗</a></p>`:''}}</article>`}}async function loadPosts(){{const q=new URLSearchParams({{q:$('#search').value,limit:'100'}});if($('#matched').value)q.set('matched',$('#matched').value);const posts=await api(`/api/targets/${{targetId}}/posts?`+q);$('#posts').innerHTML=posts.map(postHtml).join('')||'<p class="muted">No archived posts.</p>'}}
$('#target-form').onsubmit=async e=>{{e.preventDefault();const f=new FormData(e.target);await api(`/api/targets/${{targetId}}`,{{method:'PUT',body:JSON.stringify({{enabled:f.get('enabled')==='on',backfill_limit:+f.get('backfill_limit')}})}});loadTarget()}};$('#rule-form').onsubmit=async e=>{{e.preventDefault();const f=new FormData(e.target),terms=x=>String(x||'').split(',').map(x=>x.trim()).filter(Boolean),id=f.get('id'),payload={{name:f.get('name'),include_terms:terms(f.get('include')),exclude_terms:terms(f.get('exclude')),match_mode:f.get('match_mode'),enabled:f.get('enabled')==='on'}};await api(id?`/api/targets/${{targetId}}/rules/${{id}}`:`/api/targets/${{targetId}}/rules`,{{method:id?'PUT':'POST',body:JSON.stringify(payload)}});resetRuleForm();loadRules();loadPosts()}};$('#rule-cancel').onclick=resetRuleForm;$('#notify').onclick=()=>Notification.requestPermission();$('#refresh').onclick=loadPosts;$('#matched').onchange=loadPosts;let timer;$('#search').oninput=()=>{{clearTimeout(timer);timer=setTimeout(loadPosts,250)}};
function connect(){{const ws=new WebSocket(`${{location.protocol==='https:'?'wss':'ws'}}://${{location.host}}/api/live`);ws.onmessage=e=>{{const x=JSON.parse(e.data);if(x.type==='targets_updated')loadTarget();if((x.type==='post_created'||x.type==='post_updated')&&x.target_id===targetId){{loadPosts();if(x.notify&&Notification.permission==='granted')new Notification('Telegram channel alert',{{body:(x.post.text||'Matched post').slice(0,180)}})}}}};ws.onclose=()=>setTimeout(connect,2000)}}Promise.all([loadTarget(),loadRules(),loadPosts()]);connect();
</script></body></html>"""
